In [1]:
l = [1,2,3,4,5]

In [4]:
import numpy as np

In [5]:
np.array(l)

array([1, 2, 3, 4, 5])

In [6]:
a1 = np.array(l)
print(a1)

[1 2 3 4 5]


In [11]:
type(a1)

numpy.ndarray

In [27]:
a1.shape

(5,)

In [29]:
a1.ndim

1

In [21]:
A = [[1,2,3],[5,6,7],[8,9,10]]

In [22]:
np.array(A)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [23]:
A2 = np.array(A)

In [24]:
print(A2)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


In [25]:
A2.ndim

2

In [26]:
A2.shape

(3, 3)

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [39]:
print(np.eye(5,dtype = int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [36]:
B = [[1,2,3],[5,6,7],[8,9,10],[11,12,13]]

In [37]:
B1 = np.array(B)

In [38]:
print(B1)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [40]:
B1.shape

(4, 3)

In [42]:
B1.ndim

2

In [45]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [46]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [47]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [48]:
print(np.arange(1,100,2))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [49]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [50]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [52]:
print(np.zeros(5,dtype = int))

[0 0 0 0 0]


In [53]:
print(np.zeros((5,5),dtype = int))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [56]:
print(np.ones((5,5),dtype = int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [61]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [62]:
print(np.linspace(1,100,20))

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [65]:
np.random.randint(1000,9999,10)

array([3793, 4253, 5211, 3550, 5515, 7787, 8361, 2884, 1226, 7281])

In [66]:
print(np.random.randint(1000,9999,10))

[9894 8859 5840 7018 6510 4587 2674 8432 2072 5577]


In [74]:
print(np.random.randint(1000,9999,(5,5)))

[[4938 1516 6788 4210 7113]
 [9602 2398 2798 3321 3260]
 [9185 3312 7648 8698 9549]
 [1494 6849 9159 6504 4751]
 [7444 2069 6246 3271 1518]]


In [70]:
print(np.random.randn(5))

[ 0.59755666  1.72369128  0.05328423  0.80018837 -1.12269197]


In [71]:
print(np.random.randn(3,2))

[[-1.13637672  1.59582712]
 [-0.23323133  2.6149227 ]
 [ 1.46679284  0.81403047]]


In [75]:
print(np.random.rand(10))

[0.5369733  0.40161068 0.28773517 0.20069859 0.30407531 0.82622755
 0.25497803 0.43127381 0.21339458 0.90860198]


In [77]:
print(np.random.rand(5,6))

[[0.58791731 0.16499395 0.2178791  0.75662351 0.79515626 0.34934758]
 [0.1998621  0.41736321 0.08983315 0.51570901 0.54183529 0.6027277 ]
 [0.95201037 0.8647285  0.08961944 0.75225126 0.44973647 0.43288848]
 [0.14615986 0.70402604 0.64239921 0.35324851 0.7791268  0.07701445]
 [0.2816998  0.2259155  0.62208231 0.46665962 0.96506673 0.13426856]]


In [78]:
np.random.rand(5,6).shape

(5, 6)

In [79]:
K = np.linspace(1,100,20)

In [80]:
print(K)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [81]:
K.ndim

1

In [83]:
D = K.reshape(4,5)

In [84]:
D.ndim

2

In [82]:
print(K.reshape(4,5))

[[  1.           6.21052632  11.42105263  16.63157895  21.84210526]
 [ 27.05263158  32.26315789  37.47368421  42.68421053  47.89473684]
 [ 53.10526316  58.31578947  63.52631579  68.73684211  73.94736842]
 [ 79.15789474  84.36842105  89.57894737  94.78947368 100.        ]]


In [85]:
print(K.reshape(5,4))

[[  1.           6.21052632  11.42105263  16.63157895]
 [ 21.84210526  27.05263158  32.26315789  37.47368421]
 [ 42.68421053  47.89473684  53.10526316  58.31578947]
 [ 63.52631579  68.73684211  73.94736842  79.15789474]
 [ 84.36842105  89.57894737  94.78947368 100.        ]]


In [86]:
print(K.reshape(10,2))

[[  1.           6.21052632]
 [ 11.42105263  16.63157895]
 [ 21.84210526  27.05263158]
 [ 32.26315789  37.47368421]
 [ 42.68421053  47.89473684]
 [ 53.10526316  58.31578947]
 [ 63.52631579  68.73684211]
 [ 73.94736842  79.15789474]
 [ 84.36842105  89.57894737]
 [ 94.78947368 100.        ]]


In [87]:
print(K.reshape(5,5))

ValueError: cannot reshape array of size 20 into shape (5,5)

In [88]:
R = np.random.randint(1000,9999,(5,5))

In [90]:
print(R)

[[9407 7123 1814 1529 6804]
 [5070 8995 8123 5112 8625]
 [3700 7885 2001 3801 2376]
 [3308 7137 5397 7524 8629]
 [8030 3989 7316 3703 1537]]


In [91]:
R.ndim

2

In [89]:
print(R.flatten())

[9407 7123 1814 1529 6804 5070 8995 8123 5112 8625 3700 7885 2001 3801
 2376 3308 7137 5397 7524 8629 8030 3989 7316 3703 1537]


In [92]:
r = R.flatten()

In [93]:
r.ndim

1

In [100]:
list = np.random.randint(1,100,10)
print(list)
print(np.max(list))
print(np.min(list))

[61 63 61  2 23 16 82 79 95 84]
95
2


In [108]:
list = np.random.randint(1,100,10)
print(list)
list.argmax()

[80 38 80 53 65  5 55 83 37 24]


7

In [110]:
print(np.argmax(list))

7


In [109]:
list.argmin()

5

In [112]:
print(np.argmin(list))

5


In [115]:
np.random.randint(10000,99999,(7,8))

array([[27029, 85809, 13139, 27066, 31004, 79963, 33639, 86962],
       [73976, 78480, 61807, 87526, 60636, 29819, 74882, 25585],
       [71683, 88943, 37120, 55414, 50753, 61101, 96812, 80225],
       [31585, 99749, 57675, 69956, 27245, 28639, 54786, 15681],
       [25881, 86491, 61826, 95783, 32079, 38923, 85470, 73466],
       [67746, 68523, 54538, 75857, 70516, 44623, 40299, 25395],
       [10970, 12801, 86655, 15285, 27026, 93464, 23807, 43646]])

In [121]:
S = np.random.randint(10000,99999,(7,8))
print(np.random.randint(10000,99999,(7,8)))
print(np.max(S))
print(np.min(S))
print(S.flatten())

[[35459 83085 25704 97909 42562 94835 44475 53188]
 [86824 35655 43122 46723 34622 16027 42898 80620]
 [83124 61740 84971 22723 90929 77978 50966 91705]
 [16767 26289 62046 87208 57827 41436 45058 22738]
 [34685 32660 46276 60859 79092 94036 88634 65805]
 [54865 46097 76912 10834 86379 42404 52072 36678]
 [65246 12178 85785 17432 35418 77731 35192 45094]]
98763
12659
[87703 33359 86661 41847 17814 98763 29575 92034 12659 51745 43683 24355
 30816 88899 84162 58103 37525 22979 93619 91021 58021 38524 24363 47705
 98597 88438 28821 66095 53659 31528 71131 81712 70067 88078 96329 73099
 44363 84704 19804 43516 64086 81780 46995 33275 30471 25940 37302 57598
 30699 22855 54202 84669 86175 76503 51566 86904]
