In [2]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6,5,4,7,2,3]

In [3]:
print(np.array(a))

[1 2 3 4 5 6 5 4 7 2 3]


In [4]:
b = np.array(a)

In [5]:
b[0]

1

In [6]:
b[3]

4

In [7]:
b[3] = 999

In [8]:
b

array([  1,   2,   3, 999,   5,   6,   5,   4,   7,   2,   3])

In [9]:
b.sum()

1037

In [10]:
b.mean()

94.27272727272727

In [11]:
b.std()

286.1052225093199

In [12]:
b.var()

81856.19834710745

In [15]:
print(b[2:8])

[3 4 5 6 5 4]


In [13]:
A = [[1,2,3],[5,6,7],[8,9,10]]
print(np.array(A))

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


In [14]:
A2 = np.array(A)

In [22]:
A2[A2 > 5]

array([ 6,  7,  8,  9, 10])

In [23]:
A2 > 5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [16]:
A2.sum(axis = 0)
#sum of colums

array([14, 17, 20])

In [19]:
A2.sum(axis = 1)
#sum of rows

array([ 6, 18, 27])

In [19]:
A2[0,1]

2

In [20]:
A2[2,2]

10

In [22]:
A2[0:,2]

array([ 3,  7, 10])

In [24]:
A2[2,0:2]

array([8, 9])

In [25]:
A2[0:2,1:]

array([[2, 3],
       [6, 7]])

In [26]:
print(A2>5)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [28]:
print(A2[(A2>5)])

[ 6  7  8  9 10]


In [30]:
(A2 > 3) & (A2 < 9)

array([[False, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [32]:
print(A2[(A2 > 3) & (A2 < 9)])

[5 6 7 8]


In [ ]:
print(A2[(A2[0] & (A2 < 9)])

In [33]:
arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[40,50],[70,80]])

In [34]:
print(arr1)

[[10 20]
 [30 40]]


In [35]:
print(np.hstack((arr1,arr2)))

[[10 20 40 50]
 [30 40 70 80]]


In [37]:
print(np.concatenate((arr1,arr2),axis = 1))

[[10 20 40 50]
 [30 40 70 80]]


In [38]:
print(np.concatenate((arr1,arr2),axis = 0))

[[10 20]
 [30 40]
 [40 50]
 [70 80]]


In [39]:
print(np.vstack((arr1,arr2)))

[[10 20]
 [30 40]
 [40 50]
 [70 80]]


In [40]:
print(np.transpose(arr1))

[[10 30]
 [20 40]]


In [41]:
print(arr1)

[[10 20]
 [30 40]]


In [24]:
B1 = np.array([5,10,15,20])
B2 = np.array([2,5,6,7])
B3 = np.array([2])

In [25]:
B1 + B2

array([ 7, 15, 21, 27])

In [26]:
B1 - B2

array([ 3,  5,  9, 13])

In [27]:
B1 + B3

array([ 7, 12, 17, 22])

In [28]:
B1 * B2

array([ 10,  50,  90, 140])

In [29]:
B1 * B3

array([10, 20, 30, 40])

In [33]:
C1 = np.array([[5,10,15],[11,12,20],[21,22,23]])
C2 = np.array([[2,5],[6,7],[8,9]])

In [37]:
print(C1)

[[ 5 10 15]
 [11 12 20]
 [21 22 23]]


In [36]:
#multiplication we do manually or with calci by using dot or @
C1.dot(C2)

array([[190, 230],
       [254, 319],
       [358, 466]])

In [39]:
#transpose
C1.T

array([[ 5, 11, 21],
       [10, 12, 22],
       [15, 20, 23]])

In [40]:
C1 @ C2

array([[190, 230],
       [254, 319],
       [358, 466]])

In [42]:
C1.T.dot(C2)

array([[244, 291],
       [268, 332],
       [334, 422]])

In [43]:
C1.T @(C2)

array([[244, 291],
       [268, 332],
       [334, 422]])

In [44]:
import numpy as np

In [45]:
list = np.random.randint(1,100,(5,5))
print(list)
print(np.max(list))
print(np.min(list))

[[57 22 37 86 50]
 [39 82 16 72  4]
 [53 45 53 23 28]
 [28 66 96 51 69]
 [56 77 79 58 84]]
96
4


In [50]:
list = np.random.randint(1,100,10)
print(list)
print(sorted(list))

[79 35 29 52 73  4 29 14 30 49]
[4, 14, 29, 29, 30, 35, 49, 52, 73, 79]


In [51]:
a = np.array([3,4,5])

In [52]:
b = np.array([3,5,4])

In [53]:
a == b

array([ True, False, False])

In [58]:
l = np.random.randint(1,100,(5,5))
print(l)
print("\n",l[0:3,:])

[[ 1 22  2 70 20]
 [23 70 42 42  3]
 [65 77 78 10 82]
 [43 79  7 84 15]
 [48 95 92  4 63]]

 [[ 1 22  2 70 20]
 [23 70 42 42  3]
 [65 77 78 10 82]]


In [59]:
list = np.random.randint(1,100,10)
print(list)
print(sorted(list))
print(sorted(list,reverse = True))

[32 73 13 96 95 76 79 17 19 21]
[13, 17, 19, 21, 32, 73, 76, 79, 95, 96]
[96, 95, 79, 76, 73, 32, 21, 19, 17, 13]


In [79]:
list = np.random.randint(1,100,15)
print(list)
S = sorted(list,reverse = True)
print(S)

[ 8  7 86 63 69 30 65 21 14 28  8 47 15  3 93]
[93, 86, 69, 65, 63, 47, 30, 28, 21, 15, 14, 8, 8, 7, 3]


In [81]:
S[0] = -1
S

[-1, 86, 69, 65, 63, 47, 30, 28, 21, 15, 14, 8, 8, 7, 3]

In [3]:
#find the rows for which 1st value in the row is greater than 0
A = [[1,2,3,4],[3,5,4,2],[4,6,1,7],[5,3,3,1],[0,4,3,2],[1,9,8,3]]
A1 = np.array(A)
print(A1)

[[1 2 3 4]
 [3 5 4 2]
 [4 6 1 7]
 [5 3 3 1]
 [0 4 3 2]
 [1 9 8 3]]


In [6]:
for i in A1:
    if i[0] > 2:
        print(i)

[3 5 4 2]
[4 6 1 7]
[5 3 3 1]
