## Built-in Functions

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range but returns an array.

In [10]:
import numpy as np

In [ ]:
np.

## Arange
Return evenly spaced values within a given interval.

In [2]:
range(5)

range(0, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
np.arange(0,200,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195])

In [6]:
arr_zeros = np.zeros(3)
print(arr_zeros)

[0. 0. 0.]


In [ ]:
help(np.zeros)

Another cool feature is the ability to create different arrays like random arrays:   

It will create a 2 * 3 array of random numbers between 0 and 1  

# Random
Numpy also has lots of ways to create random number arrays:   

### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [7]:
arr=np.random.rand(2,3)

In [8]:
arr

array([[0.02504808, 0.6103374 , 0.97284996],
       [0.6676734 , 0.2382112 , 0.76604771]])

### randint
Return random integers from low (inclusive) to high (exclusive).

In [9]:
np.random.randint(1,10,5) # 5 is shape

array([7, 7, 2, 7, 5])

In [10]:
np.random.randint(1,10,(2,4)) # (2,4) is a shape

array([[2, 6, 7, 4],
       [2, 6, 5, 1]])

It creates an array the size of 2 * 3 with random numbers between 0 and 9 where 10 here is not inclusive.

In [11]:
np.random.randint(100,size=(2,3))

array([[56,  3, 42],
       [61, 80, 37]])

will create a 2 * 3 array of random numbers between 0 to 100.

In [ ]:
np.random.rand(2,3)* 100

## randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:   

#### interval range from (-3 to +3 )

In [ ]:
np.random.randn(5)

In [ ]:
np.random.randn(5,3)

If you need to convert the data type you can use the array.astype(dtype) 

In [ ]:
# using numpy
arr = np.array([1.0,2.0,3.0,4.0,5.0])
print(arr)
print(type(arr))
print(arr.dtype)

In [ ]:
arr1 = arr.astype(np.int64)
print(arr1)
print(type(arr1))
print(arr1.dtype)

## Identity Matrics 

- idential are one rest are zeros

In [12]:
np.eye(3) # 3 rows and 3 columns 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(0,30,10)  #0 is start, 10 is stop (inclusive) 
                     # 10 is number of values

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

if you need to convert a NumPy array to a Python list

In [15]:
arr1 = np.array([1,2,3])

In [16]:
arr2 = np.array([4,5,6])

In [17]:
arr1 + arr2 

array([5, 7, 9])

In [18]:
arr1 - arr2 

array([-3, -3, -3])

In [19]:
arr1 * 2 # Multiplication 

array([2, 4, 6])

In [20]:
arr1 / 2 # division 

array([0.5, 1. , 1.5])

In [21]:
arr1 // 2 # floor division

array([0, 1, 1], dtype=int32)

In [22]:
arr1 % 2 # modular

array([1, 0, 1], dtype=int32)

In [23]:
arr1 ** 2  # exponential 

array([1, 4, 9], dtype=int32)

In [24]:
arr = np.array([1, 2, 3, 4, 5])

### More built-in function of creating arrays
### zeros and ones
Generate arrays of zeros or ones

In [25]:
np.zeros(3) # 3 is shape (1D array shape)

array([0., 0., 0.])

In [26]:
np.zeros((3,3)) # (3,3) is row and columns shape (2D array)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones(4) 

array([1., 1., 1., 1.])

In [28]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Aggregation

In [1]:
li1 = [5,8,1,3,7,15,20]

In [3]:
li1.index(15)

5

In [4]:
li1.sort()

In [5]:
li1

[1, 3, 5, 7, 8, 15, 20]

In [6]:
min(li1)

1

In [39]:
arr = np.array([5,8,1,3,7,15,20])

In [40]:
arr

array([ 5,  8,  1,  3,  7, 15, 20])

In [42]:
print(arr.min())
print(arr.max())
print(arr.sum())

1
20
59


In [44]:
max(arr)

20

In [55]:
li1 = [ 5,  8,  7,  3,  7, 15, 20]

In [52]:
min(li1)

1

In [54]:
li1.index(1)

2

In [56]:
li1.index(min(li1))

3

In [57]:
arr

array([ 5,  8,  1,  3,  7, 15, 20])

To know position of min and max elements

In [58]:
np.argmin(arr)

2

In [59]:
np.argmax(arr)

6

In [60]:
arr2.std()  # standard Deviation

0.816496580927726

In [61]:
arr2.var()  # variance

0.6666666666666666

In [ ]:
help(max)

Reshape is when you change the number of rows and columns which gives a new view to an object.  
we have 2 rows and 3 columns and  which has converted into 3 rows and 2 columns  

In [11]:
a = np.array([(8,9,10),(11,12,13)])
print(a)

[[ 8  9 10]
 [11 12 13]]


In [12]:
b = np.array([(8,9),(10,11),(12,13)])
print(b)

[[ 8  9]
 [10 11]
 [12 13]]


In [13]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [65]:
a.shape

(2, 3)

In [66]:
b.shape

(3, 2)

In [14]:
b=b.reshape(2,3)
print(b)

[[ 8  9 10]
 [11 12 13]]


In [15]:
a+b

array([[16, 18, 20],
       [22, 24, 26]])

In [ ]:
np.append()
np.delete()
np.sort()

In [23]:
arr = np.array([5, 2, 3, 4, 1, 6, 7, 8])
arr

array([5, 2, 3, 4, 1, 6, 7, 8])

In [24]:
arr = np.append(arr, [9,10])

In [25]:
arr

array([ 5,  2,  3,  4,  1,  6,  7,  8,  9, 10])

In [26]:
arr = np.delete(arr, 1)

In [27]:
arr

array([ 5,  3,  4,  1,  6,  7,  8,  9, 10])

In [28]:
np.sort(arr)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
li1 = [1,2,3,1,2,3,1,2,3]

In [31]:
np.unique([1,2,3,1,2,3,1,2,3])

array([1, 2, 3])

In [ ]:
arr

In [32]:
print(np.sin(arr))     # sin of each element

[-0.95892427  0.14112001 -0.7568025   0.84147098 -0.2794155   0.6569866
  0.98935825  0.41211849 -0.54402111]


In [76]:
print(np.cos(arr))     # cosine of each element

[ 0.28366219 -0.41614684 -0.9899925  -0.65364362  0.54030231  0.96017029
  0.75390225 -0.14550003]


In [77]:
print(np.sqrt(arr))     # square root of each element

[2.23606798 1.41421356 1.73205081 2.         1.         2.44948974
 2.64575131 2.82842712]


In [33]:
arr

array([ 5,  3,  4,  1,  6,  7,  8,  9, 10])

In [78]:
print(np.exp(arr))     # exponentials of each element

[1.48413159e+02 7.38905610e+00 2.00855369e+01 5.45981500e+01
 2.71828183e+00 4.03428793e+02 1.09663316e+03 2.98095799e+03]


In [79]:
print(np.log(arr))     # log of each element

[1.60943791 0.69314718 1.09861229 1.38629436 0.         1.79175947
 1.94591015 2.07944154]


In [34]:
arr

array([ 5,  3,  4,  1,  6,  7,  8,  9, 10])

In [80]:
print(np.sum(arr))     # Sum of elements

36


In [81]:
print(np.std(arr))     # standard deviation

2.29128784747792


In [82]:
print(arr.max())     # maximum element of array

8


In [35]:
arr = np.array([[1, 5, 6], [4, 7, 2], [3, 1, 5]])

In [36]:
arr

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 5]])

In [85]:
arr.sum(axis=0)

array([ 8, 13, 13])

In [86]:
arr.sum(axis=1)

array([12, 13,  9])

In [37]:
arr

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 5]])

In [39]:
arr.max(axis=0)

array([4, 7, 6])

In [40]:
arr.max(axis=1)

array([6, 7, 5])

In [89]:
arr.min(axis=0)

array([1, 1, 2])

In [90]:
arr.min(axis=1)

array([1, 2, 1])

In [91]:
arr = np.array([[1, 4, 2], [3, 4, 6], [0, -1, 5]])
arr

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

In [92]:
# array elements in sorted order
print(np.sort(arr, axis=None))

[-1  0  1  2  3  4  4  5  6]


In [93]:
# sort array row wise
print(np.sort(arr, axis=1))

[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [94]:
# sort array row wise
print(np.sort(arr, axis=0))

[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
