In [9]:
#1
n = int(input("Hrs: "))
n*60*60

Hrs: 10


36000

In [14]:
#2
S = str(input())
list(S)

STRING


['S', 'T', 'R', 'I', 'N', 'G']

In [18]:
S = str(input())
list(S.split())

I am very good programmer


['I', 'am', 'very', 'good', 'programmer']

In [3]:
#3
S = input("Enter word: ")
if S[-1] == "s":
    print("plural")
else:
    print("singular")

Enter word: Apples
plural


In [4]:
#4
d = {"one":1,"two":2,"three":3}

In [5]:
list(d.items())

[('one', 1), ('two', 2), ('three', 3)]

In [12]:
sum = 0
for i in list(d.values()):
    sum = sum+i
print(sum)

6


In [27]:
#5
list1 = [5,10,15,20,25,50,20]
print(list1.index(20))
A = list1.index(20)
list1[A] = 200
print(list1)

3
[5, 10, 15, 200, 25, 50, 20]


In [32]:
s = ("string")
s[0], s[-1] = s[-1], s[0]

TypeError: 'str' object does not support item assignment

In [40]:
#7
k = lambda x:(x>=7)
l = [1,5,2,0.4,7,9,3,78,66,34]
list(filter(k,l))

[7, 9, 78, 66, 34]

In [51]:
#9
def list(*t):
    S = sorted(t)
    print(S[0])

In [52]:
list(5,2,4,7,9,3,78,66,34)

2


In [84]:
#10
file = open("AppleWikipedia.txt",mode = "x",encoding = "utf-8")

In [85]:
file.write("Apple Inc. is an American multinational technology company specializing in consumer electronics, software and online services headquartered in Cupertino, California, United States. Apple is the largest technology company by revenue (totaling US$365.8 billion in 2021) and, as of June 2022, is the world's biggest company by market capitalization, the fourth-largest personal computer vendor by unit sales and second-largest mobile phone manufacturer. It is one of the Big Five American information technology companies, alongside Alphabet, Amazon, Meta, and Microsoft.Apple was founded as Apple Computer Company on April 1, 1976, by Steve Jobs, Steve Wozniak and Ronald Wayne to develop and sell Wozniak's Apple I personal computer. It was incorporated by Jobs and Wozniak as Apple Computer, Inc. in 1977 and the company's next computer, the Apple II, became a best seller and one of the first mass-produced microcomputers. Apple went public in 1980 to instant financial success. The company developed computers featuring innovative graphical user interfaces, including the 1984 original Macintosh, announced that year in a critically acclaimed advertisement. By 1985, the high cost of its products and power struggles between executives caused problems. Wozniak stepped back from Apple amicably and pursued other ventures, while Jobs resigned bitterly and founded NeXT, taking some Apple employees with him.As the market for personal computers expanded and evolved throughout the 1990s, Apple lost considerable market share to the lower-priced duopoly of the Microsoft Windows operating system on Intel-powered PC clones (also known as Wintel). In 1997, weeks away from bankruptcy, the company bought NeXT to resolve Apple's unsuccessful operating system strategy and entice Jobs back to the company. Over the next decade, Jobs guided Apple back to profitability through a number of tactics including introducing the iMac, iPod, iPhone and iPad to critical acclaim, launching Think different and other memorable advertising campaigns, opening the Apple Store retail chain, and acquiring numerous companies to broaden the company's product portfolio. When Jobs resigned in 2011 for 12 health reasons, and died two months later, he was succeeded as CEO by Tim Cook.Apple became the first publicly traded U.S. company to be valued at over $1 trillion in August 2018, then $2 trillion in August 2020, and most recently $3 trillion in January 2022. The company receives criticism regarding the labor practices of its contractors, its environmental practices, and its business ethics, including anti-competitive practices and materials sourcing. Nevertheless, the company has a large following and enjoys a high level of brand loyalty. It is ranked as one of the world's most valuable brands.")

2787

In [86]:
file.close()

In [87]:
file = open("AppleWikipedia.txt",mode = "r",encoding = "utf-8")
data = file.read()

In [88]:
A = data.lower()
B = A.split()

In [89]:
for i in B:
    if i[0] == "s":
        print(i)

specializing
software
services
states.
sales
second-largest
steve
steve
sell
seller
success.
struggles
stepped
some
share
system
system
strategy
store
succeeded
sourcing.


In [90]:
for i in B:
    if i[-1] == "y" and i[-2]=="l":
        print(i)

critically
amicably
bitterly
duopoly
publicly
recently


In [92]:
for i in B:
    if i.isdigit():
        if len(i) == 4:
            print(i)

1977
1980
1984
2011


In [93]:
file.close()

In [33]:
#11
class details:
    def __init__(self,name,age,height):
        self.n = name
        self.a = age
        self.h = height
    def get_string(self):
        global A
        A = input()
    def print_string(self):
        print("name:",self.n,"age:",self.a,"height:",self.h)
        print(A+" "+str(self.h))

In [34]:
K = details("Kush",21,5.4)

In [35]:
K.get_string()

I am Kushmitha


In [36]:
K.print_string()

name: Kush age: 21 height: 5.4
I am Kushmitha 5.4


In [40]:
class Rectangle:
    def __init__(self,length,breadth):
        self.l = length
        self.b = breadth
    def area(self):
        print("Area of rectangle:",self.l*self.b)

class circle:
    def __init__(self,radius):
        self.r = radius
    def area(self):
        pi = 3.14
        print("area of circle:",pi*self.r*self.r)


A = Rectangle(3,5)
A.area()
B = circle(5.0)
B.area()

Area of rectangle: 15
area of circle: 78.5


In [1]:
first = 10
second = 20
temp = first
first = second
second = temp

In [2]:
print(first,second)

20 10


In [14]:
def swap(a,b,c):
    d = c[2]
    c[2] = c[5]
    c[5] = d
    return c
    

In [15]:
swap(2,5,"kushmitha")

TypeError: 'str' object does not support item assignment

In [1]:
c = "kushmitha"
d = c[2]
c[2] = c[5]
c[5] = d

TypeError: 'str' object does not support item assignment

In [19]:
c = "kushmitha"
c[2]

's'

In [20]:
c[5]

'i'

In [22]:
c[5] = d

TypeError: 'str' object does not support item assignment

In [2]:
import numpy as np

In [3]:
list = np.random.randint(1,100,(5,5))
print(list)
print(np.max(list))
print(np.min(list))

[[44 97 23 28 17]
 [93 93  6 72 11]
 [12 93 77 89 11]
 [40 80 86 18 96]
 [ 5 52 36 16 82]]
97
5


In [11]:
list = np.random.randint(1,100,10)
print(list)
print(sorted(np.max(list)))

[38 87 63 46 93 31 93 90 91 12]


TypeError: 'numpy.int32' object is not iterable